{{- if .Values.configmap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxlb-config
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Chart.Name }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: proxlb
    app.kubernetes.io/managed-by: Helm
data:
  proxlb.yaml: |
{{ toYaml .Values.configmap.config | indent 4 }}
{{ end }}