apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  replicas: 1 # Number of replicas cannot be more than 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: proxlb
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.extraArgs.dryRun }}
          - --dry-run
        {{- end }}
        volumeMounts:
          - name: config
            mountPath: /etc/proxlb/proxlb.yaml
            subPath: proxlb.yaml
      volumes:
        - name: config
          configMap:
            name: proxlb-config