name: "Build Container Image: ARM64"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build arm64 image and save as tar
      run: |
        docker buildx build \
          --platform linux/arm64 \
          --load \
          -t proxlb-image:arm64 \
          .

        docker save proxlb-image:arm64 -o proxlb_image_arm64.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxlb-image-arm64
        path: proxlb_image_arm64.tar
